openapi: 3.1.0
info:
  title: Super Voice Anphropic Namespace
  version: '0.1.0'
  description: Delegated contract for Anphropic endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /anphropic/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1chat~1completions
  /anphropic/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1embeddings
  /anphropic/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1images~1generations
  /anphropic/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1audio~1transcriptions
  /anphropic/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1audio~1speech
  /anphropic/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1video~1generations
  /anphropic/models:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1models
  /anphropic/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1batches
  /anphropic/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1anphropic~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
