openapi: 3.1.0
info:
  title: Super Voice Gemini Namespace
  version: '0.1.0'
  description: Delegated contract for Gemini endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /gemini/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1chat~1completions
  /gemini/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1embeddings
  /gemini/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1images~1generations
  /gemini/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1audio~1transcriptions
  /gemini/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1audio~1speech
  /gemini/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1video~1generations
  /gemini/models:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1models
  /gemini/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1batches
  /gemini/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1gemini~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
