openapi: 3.1.0
info:
  title: Super Voice Hugging Face Namespace
  version: '0.1.0'
  description: Delegated contract for Hugging Face endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /huggingface/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1chat~1completions
  /huggingface/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1embeddings
  /huggingface/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1images~1generations
  /huggingface/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1audio~1transcriptions
  /huggingface/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1audio~1speech
  /huggingface/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1video~1generations
  /huggingface/models:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1models
  /huggingface/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1batches
  /huggingface/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1huggingface~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
