openapi: 3.1.0
info:
  title: Super Voice MiniMax Namespace
  version: '0.1.0'
  description: Delegated contract for MiniMax endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /minimax/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1chat~1completions
  /minimax/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1embeddings
  /minimax/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1images~1generations
  /minimax/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1audio~1transcriptions
  /minimax/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1audio~1speech
  /minimax/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1video~1generations
  /minimax/models:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1models
  /minimax/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1batches
  /minimax/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1minimax~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
