openapi: 3.1.0
info:
  title: Super Voice OpenAI Namespace
  version: '0.1.0'
  description: Delegated contract for OpenAI endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /openai/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1chat~1completions
  /openai/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1embeddings
  /openai/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1images~1generations
  /openai/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1audio~1transcriptions
  /openai/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1audio~1speech
  /openai/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1video~1generations
  /openai/models:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1models
  /openai/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1batches
  /openai/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1openai~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
