openapi: 3.1.0
info:
  title: Super Voice Open Router Namespace
  version: '0.1.0'
  description: Delegated contract for Open Router endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /openrouter/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1chat~1completions
  /openrouter/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1embeddings
  /openrouter/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1images~1generations
  /openrouter/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1audio~1transcriptions
  /openrouter/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1audio~1speech
  /openrouter/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1video~1generations
  /openrouter/models:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1models
  /openrouter/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1batches
  /openrouter/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1openrouter~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
