openapi: 3.1.0
info:
  title: Super Voice PerplexetyAI Namespace
  version: '0.1.0'
  description: Delegated contract for PerplexetyAI endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /perplexety/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1chat~1completions
  /perplexety/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1embeddings
  /perplexety/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1images~1generations
  /perplexety/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1audio~1transcriptions
  /perplexety/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1audio~1speech
  /perplexety/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1video~1generations
  /perplexety/models:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1models
  /perplexety/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1batches
  /perplexety/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1perplexety~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
