openapi: 3.1.0
info:
  title: Super Voice Qwen Namespace
  version: '0.1.0'
  description: Delegated contract for Qwen endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /qwen/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1chat~1completions
  /qwen/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1embeddings
  /qwen/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1images~1generations
  /qwen/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1audio~1transcriptions
  /qwen/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1audio~1speech
  /qwen/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1video~1generations
  /qwen/models:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1models
  /qwen/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1batches
  /qwen/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1qwen~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
