openapi: 3.1.0
info:
  title: Super Voice Vertex Namespace
  version: '0.1.0'
  description: Delegated contract for Vertex endpoints in the Super Voice SuperAPI.
servers:
  - url: https://api.supervoice.dev
paths:
  /vertex/chat/completions:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1chat~1completions
  /vertex/embeddings:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1embeddings
  /vertex/images/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1images~1generations
  /vertex/audio/transcriptions:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1audio~1transcriptions
  /vertex/audio/speech:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1audio~1speech
  /vertex/video/generations:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1video~1generations
  /vertex/models:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1models
  /vertex/batches:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1batches
  /vertex/jobs/{id}:
    $ref: ../superapi.openapi.yaml#/paths/~1vertex~1jobs~1{id}
components:
  schemas:
    ChatCompletionRequest:
      $ref: ../schemas/chat_request.json
    ChatCompletionResponse:
      $ref: ../schemas/chat_response.json
    EmbeddingsRequest:
      $ref: ../schemas/embeddings_request.json
    EmbeddingsResponse:
      $ref: ../schemas/embeddings_response.json
    ImageGenerationRequest:
      $ref: ../schemas/image_request.json
    TextToSpeechRequest:
      $ref: ../schemas/tts_request.json
    AudioTranscriptionRequest:
      $ref: ../schemas/asr_request.json
    ErrorResponse:
      $ref: ../schemas/error.json
  responses:
    ErrorResponse:
      $ref: ../superapi.openapi.yaml#/components/responses/ErrorResponse
  parameters:
    XVendorHeader:
      $ref: ../superapi.openapi.yaml#/components/parameters/XVendorHeader
    VendorQuery:
      $ref: ../superapi.openapi.yaml#/components/parameters/VendorQuery
