services:
  superapi:
    build:
      context: .
    image: superapi_server:latest
    env_file:
      - .env
    environment:
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-8080}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT:-8080}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  # Enable the observability profile to run the collector, Prometheus, and Grafana:
  #   docker compose --profile observability up --build
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./config/observability/otel-collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    profiles:
      - observability

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./config/observability/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    profiles:
      - observability

  grafana:
    image: grafana/grafana:10.4.5
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    profiles:
      - observability

volumes:
  grafana-data:
